name: development
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  video_player: ^2.7.0
  pin_code_fields: ^7.1.0
  google_nav_bar: ^5.0.6
  dotted_border: ^2.0.0+3
  flutter_countdown_timer: ^4.1.0
  file_picker: ^5.3.2
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  google_fonts: ^4.0.3
  country_code_picker: ^3.0.0
  intl_phone_number_input: ^0.7.0
  intl_phone_field: ^3.2.0
  flutter_inset_box_shadow: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/GameButton/image1.png
    - assets/Final.mp4
    - assets/GameButton/
    - assets/profile/
    - assets/Quizz/
    - assets/Game/
    - assets/GameHistory/
    - assets/Transaction/
    - assets/Refer/
    - assets/sucessful/
    - assets/widrwal/
    - assets/Prize/
    - assets/Menu/
    - assets/NavBar/
    - assets/Signup/
    - assets/ButtonBar/
    - assets/GameButton/reward.png
    - assets/GameButton/trophy.svg
#    - assets/GameButton/fruit.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CeraProBlack
      fonts:
        - asset: assets/fonts/Cera Pro Black.ttf
    - family: CeraProBlacki
      fonts:
        - asset: assets/fonts/Cera Pro Black Italic.ttf
    - family: CeraProBold
      fonts:
        - asset: assets/fonts/Cera Pro Bold.ttf
    - family: CeraProLight
      fonts:
        - asset: assets/fonts/Cera Pro Light.ttf
    - family: CeraProMedium
      fonts:
        - asset: assets/fonts/Cera Pro Medium.ttf
    - family: CeraProRegularItaclic
      fonts:
        - asset: assets/fonts/Cera Pro Regular Italic.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
